# SITE CONFIGURATION
title: z0nka1 # your site title
author: z0nka1 # You :P
description: > # Meta description of Homepage
  个人博客
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://z0nka1.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/z0nka1
    - https://www.facebook.com/z0nka1
    - https://github.com/z0nka1

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  # - {name: 'Resume', link: '/resume'}

tagline: >
  个人博客发布平台

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: liang3075435@163.com # email for form submission

# twitter_username: z0nka1 # replace with your_twitter_username or comment to remove link from footer
github_username:  z0nka1 # replace with your_github_username or comment to remove link from footer
# instagram_username: z0nka1 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
